### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by santoshdawre** [sensepost/kwetza#51]
──(root💀kali)-[~/Desktop/kwetza]
└─# python kwetza.py MX.apk TCP 192.168.43.247  4444 yes                       
  File "/root/Desktop/kwetza/kwetza.py", line 17
    print "[*] BYTING TCP COMMS"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[*] BYTING TCP COMMS")?

**Comment by L1u2c3a4s5862** [comment]
I had this error I think is because of bs4, but I have installed bs4: pip install beautifulsoup4. 

python kwetza.py com.instabridge.android_14633_apps.evozi.com.apk TCP 172.28.30.187 4444 yes
Traceback (most recent call last):
  File "kwetza.py", line 5, in <module>
    from bs4 import BeautifulSoup as Soup
ImportError: No module named bs4
